#!/bin/sh
# Copyright 2003 Alberto Gonzalez Iniesta <agi@agi.as>
# Licensed under the GNU General Public License, version 2.  See the file
# /usr/share/common-licenses/GPL or <http://www.gnu.org/copyleft/gpl.txt>.
#
set -e
test $DEBIAN_SCRIPT_DEBUG && set -v -x

# Use debconf
. /usr/share/debconf/confmodule

# Do we want to create /dev/net/tun?
if [ ! -e /dev/net/tun ]; then
  db_input medium openvpn/create_tun || true
  db_go
fi

# Do we want to move the old S20 symlinks to S18 ones?
if [ -n "$2" ] ; then
  if `dpkg --compare-versions "$2" lt 1.4.3-2`; then
    db_input medium openvpn/change_init || true
    db_go
  fi
fi

# do we want to stop opevpn while upgrading?
db_input medium openvpn/stop2upgrade || true
db_go

db_stop

exit 0
# vim: set ai et sts=2 sw=2 tw=0:
